{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintLang where

-- pretty-printer generated by the BNF converter

import AbsLang
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Prog where
  prt i e = case e of
    Program stm -> prPrec i 0 (concatD [prt 0 stm])

instance Print Exp where
  prt i e = case e of
    EAdd exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "+"), prt 1 exp2])
    ESub exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "-"), prt 1 exp2])
    EMul exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "*"), prt 2 exp2])
    EDiv exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "/"), prt 2 exp2])
    EInt n -> prPrec i 2 (concatD [prt 0 n])
    ECall id exp -> prPrec i 0 (concatD [prt 0 id, doc (showString "("), prt 0 exp, doc (showString ")")])
    EInc id -> prPrec i 0 (concatD [prt 0 id, doc (showString "++")])
    EDec id -> prPrec i 0 (concatD [prt 0 id, doc (showString "--")])
    EVar id -> prPrec i 0 (concatD [prt 0 id])
    BTrue -> prPrec i 1 (concatD [doc (showString "true")])
    BFalse -> prPrec i 1 (concatD [doc (showString "false")])
    BLe exp1 exp2 -> prPrec i 1 (concatD [prt 0 exp1, doc (showString "<="), prt 0 exp2])
    BLt exp1 exp2 -> prPrec i 1 (concatD [prt 0 exp1, doc (showString "<"), prt 0 exp2])
    BGe exp1 exp2 -> prPrec i 1 (concatD [prt 0 exp1, doc (showString ">="), prt 0 exp2])
    BGt exp1 exp2 -> prPrec i 1 (concatD [prt 0 exp1, doc (showString ">"), prt 0 exp2])
    BEq exp1 exp2 -> prPrec i 1 (concatD [prt 0 exp1, doc (showString "=="), prt 0 exp2])
    BCon exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "and"), prt 1 exp2])
    BAlt exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "or"), prt 1 exp2])
    BNeg exp -> prPrec i 0 (concatD [doc (showString "not"), prt 1 exp])
    FLam id stm -> prPrec i 0 (concatD [doc (showString "lambda"), doc (showString "("), prt 0 id, doc (showString ")"), doc (showString ":"), prt 0 stm])

instance Print Stm where
  prt i e = case e of
    SAss id exp -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 exp])
    SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), prt 0 exp, doc (showString "do"), prt 0 stm])
    SIf exp stm -> prPrec i 0 (concatD [doc (showString "if"), prt 0 exp, doc (showString "then"), prt 0 stm])
    SIfEl exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 exp, doc (showString "then"), prt 0 stm1, doc (showString "else"), prt 0 stm2])
    SBlock decls stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 decls, prt 0 stms, doc (showString "}")])
    SPrint exp -> prPrec i 0 (concatD [doc (showString "print"), prt 0 exp])
    SFor id exp1 exp2 stm -> prPrec i 0 (concatD [doc (showString "for"), prt 0 id, doc (showString "ranging"), doc (showString "from"), prt 0 exp1, doc (showString "to"), prt 0 exp2, doc (showString "do"), prt 0 stm])
    SRet exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp])
    SYield exp -> prPrec i 0 (concatD [doc (showString "yield"), prt 0 exp])
  prtList _ [] = (concatD [])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
instance Print Decl where
  prt i e = case e of
    DVar type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
    DFun id1 id2 stm -> prPrec i 0 (concatD [doc (showString "function"), prt 0 id1, doc (showString "("), prt 0 id2, doc (showString ")"), prt 0 stm])
    DRFun id1 id2 stm -> prPrec i 0 (concatD [doc (showString "function"), prt 0 id1, doc (showString "("), doc (showString "ref"), prt 0 id2, doc (showString ")"), prt 0 stm])
    DFFun id1 id2 stm -> prPrec i 0 (concatD [doc (showString "function"), prt 0 id1, doc (showString "("), doc (showString "fun"), prt 0 id2, doc (showString ")"), prt 0 stm])
  prtList _ [] = (concatD [])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString "."), prt 0 xs])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Type where
  prt i e = case e of
    TInt -> prPrec i 0 (concatD [doc (showString "int")])
    TBool -> prPrec i 0 (concatD [doc (showString "bool")])


